// toolset-vue/src/components/Registration.vue
<template>
  <form>
    <div>
      <label>
        Username
        <input placeholder="Username" type="text">
        <!-- <ng-container *ngIf="username.touched && username.errors">
        <span class="error" *ngIf="username.errors.required">Required</span>
        <span class="error" *ngIf="username.errors.minlength">Username must be at least 4 characters long</span>
      </ng-container>
      <ng-container *ngIf="username.touched && !username.errors && username.warnings">
        <span class="warning" *ngIf="username.warnings.minlength">Username should be at least 6 characters long</span>
        </ng-container>-->
      </label>
    </div>
    <div>
      <label>
        Password
        <input placeholder="Password" type="password">
        <!-- <ng-container *ngIf="password.touched && password.errors">
        <span class="error" *ngIf="password.errors.required">Required</span>
        <span class="error" *ngIf="password.errors.minlength">Password must be at least 4 characters long</span>
      </ng-container>
      <ng-container *ngIf="password.touched && !password.errors && password.warnings">
        <span class="warning" *ngIf="password.warnings.minlength">Password should be at least 6 characters long</span>
        </ng-container>-->
      </label>
    </div>
    <div>
      <label>
        Password confirm
        <input placeholder="Password confirm" type="password">
        <!-- <ng-container *ngIf="passwordConfirm.touched && passwordConfirm.errors">
        <span class="error" *ngIf="passwordConfirm.errors.required">Required</span>
        <span class="error" *ngIf="passwordConfirm.errors.minlength">Password must be at least 4 characters long</span>
        <span class="error" *ngIf="passwordConfirm.errors.noMatch">Passwords do not match</span>
      </ng-container>
      <ng-container *ngIf="passwordConfirm.touched && !passwordConfirm.errors && passwordConfirm.warnings">
        <span class="warning" *ngIf="passwordConfirm.warnings.minlength">Password confirm should be at least 6
          characters long</span>
        </ng-container>-->
      </label>
    </div>
    <div>
      <label>
        Display name
        <input placeholder="Display name" type="text">
        <!-- <ng-container *ngIf="displayName.touched && displayName.errors">
        <span class="error" *ngIf="displayName.errors.required">Required</span>
        </ng-container>-->
      </label>
    </div>
    <button type="submit">Send</button>
  </form>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

@Component
export default class Registration extends Vue {
  //   @Prop() private msg!: string;
}
</script>

<style lang="scss" scoped>
</style>

// toolset-react/src/components/registration/registration.tsx
import React from 'react';
import './registration.css';
import { Field } from 'redux-form';
import textField from '../textField/index';

export const validate = (values: any) => {
    const errors: any = {};

    if (!values.username) {
        errors.username = 'Required';
    } else {
        if (values.username.length < 4) {
            errors.username = 'Username must be at least 4 characters long';
        }
    }

    if (!values.password) {
        errors.password = 'Required';
    } else {
        if (values.password.length < 4) {
            errors.password = 'Password must be at least 4 characters long';
        }
    }

    if (!values.passwordConfirm) {
        errors.passwordConfirm = 'Required';
    } else {
        if (values.passwordConfirm.length < 4) {
            errors.passwordConfirm = 'Password must be at least 4 characters long';
        }
    }

    if (values.password !== values.passwordConfirm) {
        errors.passwordConfirm = 'Passwords do not match';
    }

    if (!values.displayName) {
        errors.displayName = 'Required';
    }

    return errors;
};

export const warn = (values: any) => {
    const warnings: any = {};

    if (values.username && values.username.length < 6) {
        warnings.username = 'Username should be at least 6 characters long';
    }

    if (values.password && values.password.length < 6) {
        warnings.password = 'Password should be at least 6 characters long';
    }

    if (values.passwordConfirm && values.passwordConfirm.length < 6) {
        warnings.passwordConfirm = 'Password should be at least 6 characters long';
    }

    return warnings;
};

const Registration = (props: any) => {
    const onSubmit = (values: any) => {
        props.registration(values);
    };

    return (
        <form onSubmit={props.handleSubmit(onSubmit)}>
            <div>
                <Field
                    name="username"
                    component={textField}
                    type="text"
                    label="Username"
                />
            </div>
            <div>
                <Field
                    name="password"
                    component={textField}
                    type="password"
                    label="Password"
                />
            </div>
            <div>
                <Field
                    name="passwordConfirm"
                    component={textField}
                    type="password"
                    label="Password confirm"
                />
            </div>
            <div>
                <Field
                    name="displayName"
                    component={textField}
                    type="text"
                    label="Display name"
                />
            </div>
            <input type="submit" value="Send" disabled={props.pristine || props.submitting || props.invalid} />
        </form>
    )
};

export default Registration;
