// toolset-react-js/src/components/login/login.js
import React from 'react';
import './login.css';
import { Field } from 'redux-form';

const Login = (props) => {
    const onSubmit = (values) => {
        props.login(values);
    };

    return (
        <form onSubmit={props.handleSubmit(onSubmit)}>
            <div>
                <label>
                    Username
                    <Field
                        name="username"
                        component="input"
                        type="text" />
                </label>
            </div>
            <div>
                <label>
                    Password
                    <Field
                        name="password"
                        component="input"
                        type="password" />
                </label>
            </div>
            <input type="submit" value="Send"></input>
        </form>
    )
};

export default Login;

// toolset-vue/src/components/Login.vue
<template>
  <form>
    <div>
      <label>
        Username
        <input placeholder="Username" type="text">
        <!-- <ng-container *ngIf="username.touched && username.errors">
        <span class="error" *ngIf="username.errors.required">Required</span>
        </ng-container>-->
      </label>
    </div>
    <div>
      <label>
        Password
        <input placeholder="Password" type="password">
        <!-- <ng-container *ngIf="password.touched && password.errors">
        <span class="error" *ngIf="password.errors.required">Required</span>
        </ng-container>-->
      </label>
    </div>
    <button type="submit">Send</button>
  </form>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

@Component
export default class Login extends Vue {
  //   @Prop() private msg!: string;
}
</script>

<style lang="scss" scoped>
</style>
