// toolset-react-js/src/components/navigationBar/navigationBar.js
import React from 'react';
import './navigationBar.css';
import { Link } from "react-router-dom";

const NavigationBar = () => {
    return (
        <nav>
            <ul>
                <li>
                    <Link to='/registration' >
                        REGISTRATION
                    </Link>
                </li>
                <li>
                    <Link to='/login' >
                        LOGIN
                    </Link>
                </li>
            </ul>
        </nav>
    );
};

export default NavigationBar;

// toolset-vue/src/components/NavigationBar.vue
<template>
  <nav>
    <ul>
      <li>
        <router-link to="/registration">REGISTRATION</router-link>
      </li>
      <li>
        <router-link to="/login">LOGIN</router-link>
      </li>
    </ul>
  </nav>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

@Component
export default class NavigationBar extends Vue {
//   @Prop() private msg!: string;
}
</script>

<style lang="scss" scoped>
</style>
