// toolset-vue/src/components/Registration.vue
<template>
  <form @submit.prevent="onSubmit">
    <div>
      <label>
        Username
        <input placeholder="Username" type="text">
        <!-- <ng-container *ngIf="username.touched && username.errors">
        <span class="error" *ngIf="username.errors.required">Required</span>
        <span class="error" *ngIf="username.errors.minlength">Username must be at least 4 characters long</span>
      </ng-container>
      <ng-container *ngIf="username.touched && !username.errors && username.warnings">
        <span class="warning" *ngIf="username.warnings.minlength">Username should be at least 6 characters long</span>
        </ng-container>-->
      </label>
    </div>
    <div>
      <label>
        Password
        <input placeholder="Password" type="password">
        <!-- <ng-container *ngIf="password.touched && password.errors">
        <span class="error" *ngIf="password.errors.required">Required</span>
        <span class="error" *ngIf="password.errors.minlength">Password must be at least 4 characters long</span>
      </ng-container>
      <ng-container *ngIf="password.touched && !password.errors && password.warnings">
        <span class="warning" *ngIf="password.warnings.minlength">Password should be at least 6 characters long</span>
        </ng-container>-->
      </label>
    </div>
    <div>
      <label>
        Password confirm
        <input placeholder="Password confirm" type="password">
        <!-- <ng-container *ngIf="passwordConfirm.touched && passwordConfirm.errors">
        <span class="error" *ngIf="passwordConfirm.errors.required">Required</span>
        <span class="error" *ngIf="passwordConfirm.errors.minlength">Password must be at least 4 characters long</span>
        <span class="error" *ngIf="passwordConfirm.errors.noMatch">Passwords do not match</span>
      </ng-container>
      <ng-container *ngIf="passwordConfirm.touched && !passwordConfirm.errors && passwordConfirm.warnings">
        <span class="warning" *ngIf="passwordConfirm.warnings.minlength">Password confirm should be at least 6
          characters long</span>
        </ng-container>-->
      </label>
    </div>
    <div>
      <label>
        Display name
        <input placeholder="Display name" type="text">
        <!-- <ng-container *ngIf="displayName.touched && displayName.errors">
        <span class="error" *ngIf="displayName.errors.required">Required</span>
        </ng-container>-->
      </label>
    </div>
    <button type="submit">Send</button>
  </form>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

@Component
export default class Registration extends Vue {
  //   @Prop() private msg!: string;
  public onSubmit() {
    console.log('submit');
  }
}
</script>

<style lang="scss" scoped>
</style>

// toolset-angular/src/app/auth/registration/registration.component.ts
import { Component, OnInit } from '@angular/core';
import { AuthService } from '../auth.service';
import { FormGroup, FormControl, Validators, ValidatorFn } from '@angular/forms';

const passwordMatchValidator: ValidatorFn = (form) => {
  const password = form.get('password').value;
  const passwordConfirm = form.get('passwordConfirm').value;

  return password && passwordConfirm && password !== passwordConfirm
    ? { 'passwordsNotMatch': true }
    : null;
};

@Component({
  selector: 'app-registration',
  templateUrl: './registration.component.html',
  styleUrls: ['./registration.component.scss']
})
export class RegistrationComponent implements OnInit {
  form: FormGroup;

  constructor(private authService: AuthService) { }

  get username() {
    return this.form.get('username');
  }

  get password() {
    return this.form.get('password');
  }

  get passwordConfirm() {
    return this.form.get('passwordConfirm');
  }

  get displayName() {
    return this.form.get('displayName');
  }

  onSubmit() {
    if (this.form.valid) {
      this.authService.registration({
        username: this.username.value,
        password: this.password.value,
        displayName: this.displayName.value
      })
        .subscribe((response) => {
          console.log(response);
        });
    }
  }

  ngOnInit() {
    this.form = new FormGroup({
      'username': new FormControl(null, [
        Validators.required,
        Validators.minLength(4),
      ]),
      'password': new FormControl(null, [
        Validators.required,
        Validators.minLength(4),
      ]),
      'passwordConfirm': new FormControl(null, [
        Validators.required,
        Validators.minLength(4),
      ]),
      'displayName': new FormControl(null, [
        Validators.required
      ])
    }, [
        passwordMatchValidator
      ]);
  }
}

<form [formGroup]="form" (ngSubmit)="onSubmit()">
  <div>
    <label>
      Username
      <input placeholder="Username" type="text" formControlName="username">
      <ng-container *ngIf="username.touched && username.errors">
        <span class="error" *ngIf="username.errors.required">Required</span>
        <span class="error" *ngIf="username.errors.minlength">Username must be at least 4 characters long</span>
      </ng-container>
      <ng-container *ngIf="username.touched && !username.errors && username.warnings">
        <span class="warning" *ngIf="username.warnings.minlength">Username should be at least 6 characters long</span>
      </ng-container>
    </label>
  </div>
  <div>
    <label>
      Password
      <input placeholder="Password" type="password" formControlName="password">
      <ng-container *ngIf="password.touched && password.errors">
        <span class="error" *ngIf="password.errors.required">Required</span>
        <span class="error" *ngIf="password.errors.minlength">Password must be at least 4 characters long</span>
      </ng-container>
      <ng-container *ngIf="password.touched && !password.errors && password.warnings">
        <span class="warning" *ngIf="password.warnings.minlength">Password should be at least 6 characters long</span>
      </ng-container>
    </label>
  </div>
  <div>
    <label>
      Password confirm
      <input placeholder="Password confirm" type="password" formControlName="passwordConfirm">
      <ng-container *ngIf="passwordConfirm.touched && passwordConfirm.errors">
        <span class="error" *ngIf="passwordConfirm.errors.required">Required</span>
        <span class="error" *ngIf="passwordConfirm.errors.minlength">Password must be at least 4 characters long</span>
        <span class="error" *ngIf="passwordConfirm.errors.noMatch">Passwords do not match</span>
      </ng-container>
      <ng-container *ngIf="passwordConfirm.touched && !passwordConfirm.errors && passwordConfirm.warnings">
        <span class="warning" *ngIf="passwordConfirm.warnings.minlength">Password confirm should be at least 6
          characters long</span>
      </ng-container>
    </label>
  </div>
  <div>
    <label>
      Display name
      <input placeholder="Display name" type="text" formControlName="displayName">
      <ng-container *ngIf="displayName.touched && displayName.errors">
        <span class="error" *ngIf="displayName.errors.required">Required</span>
      </ng-container>
    </label>
  </div>
  <button type="submit" [disabled]="form.invalid">Send</button>
</form>
