// toolset-react/src/components/login/login.tsx
import React from 'react';
import './login.css';
import { Field } from 'redux-form';
import textField from './../textField/index';

export const validate = (values: any) => {
    const errors: any = {};

    if (!values.username) {
        errors.username = 'Required';
    } else {
        if (values.username.length < 4) {
            errors.username = 'Username must be at least 4 characters long';
        }
    }

    if (!values.password) {
        errors.password = 'Required';
    } else {
        if (values.password.length < 4) {
            errors.password = 'Password must be at least 4 characters long';
        }
    }

    return errors;
};

const Login = (props: any) => {
    const onSubmit = (values: any) => {
        props.login(values);
    };

    return (
        <form onSubmit={props.handleSubmit(onSubmit)}>
            <div>
                <Field
                    name="username"
                    component={textField}
                    type="text"
                    label="Username"
                />
            </div>
            <div>
                <Field
                    name="password"
                    component={textField}
                    type="password"
                    label="Password"
                />
            </div>
            <input type="submit" value="Send" disabled={props.pristine || props.submitting || props.invalid} />
        </form>
    )
};

export default Login;

// toolset-angular/src/app/auth/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormControl, Validators } from '@angular/forms';
import { AuthService } from '../auth.service';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss']
})
export class LoginComponent implements OnInit {
  form: FormGroup;

  constructor(private authService: AuthService) { }

  get username() {
    return this.form.get('username');
  }

  get password() {
    return this.form.get('password');
  }

  onSubmit() {
    if (this.form.valid) {
      this.authService.login({
        username: this.username.value,
        password: this.password.value
      })
        .subscribe((response) => {
          console.log(response);
        });
    }
  }

  ngOnInit() {
    this.form = new FormGroup({
      'username': new FormControl(null, [
        Validators.required,
        Validators.minLength(4),
        (control) => {
          const warning = Validators.minLength(6)(control);
          if (warning) {
            (control as any).warnings = warning;
          }
          return null;
        }
      ]),
      'password': new FormControl(null, [
        Validators.required,
        Validators.minLength(4)
      ])
    });
  }
}

<form [formGroup]="form" (ngSubmit)="onSubmit()">
  <div>
    <label>
      Username
      <input placeholder="Username" type="text" formControlName="username">
      <ng-container *ngIf="username.touched && username.errors">
        <span class="error" *ngIf="username.errors.required">Required</span>
        <span class="error" *ngIf="username.errors.minlength">Username must be at least 4 characters long</span>
      </ng-container>
    </label>
  </div>
  <div>
    <label>
      Password
      <input placeholder="Password" type="password" formControlName="password">
      <ng-container *ngIf="password.touched && password.errors">
        <span class="error" *ngIf="password.errors.required">Required</span>
        <span class="error" *ngIf="password.errors.minlength">Password must be at least 4 characters long</span>
      </ng-container>
    </label>
  </div>
  <button type="submit" [disabled]="form.invalid">Send</button>
</form>
