// toolset-vue/src/components/Login.vue
<template>
  <form @submit.prevent="onSubmit">
    <div>
      <label>
        Username
        <input placeholder="Username" type="text" v-model="username">
        <!-- <ng-container *ngIf="username.touched && username.errors">
        <span class="error" *ngIf="username.errors.required">Required</span>
        </ng-container>-->
      </label>
    </div>
    <div>
      <label>
        Password
        <input placeholder="Password" type="password" v-model="password">
        <!-- <ng-container *ngIf="password.touched && password.errors">
        <span class="error" *ngIf="password.errors.required">Required</span>
        </ng-container>-->
      </label>
    </div>
    <button type="submit">Send</button>
  </form>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

@Component
export default class Login extends Vue {
  public username: string = '';
  public password: string = '';

  //   @Prop() private msg!: string;
  public onSubmit() {
    console.log('submit', this.username, this.password);
  }
}
</script>

<style lang="scss" scoped>
</style>

// toolset-angular/src/app/auth/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormControl, Validators } from '@angular/forms';
import { AuthService } from '../auth.service';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss']
})
export class LoginComponent implements OnInit {
  form: FormGroup;

  constructor(private authService: AuthService) { }

  get username() {
    return this.form.get('username');
  }

  get password() {
    return this.form.get('password');
  }

  onSubmit() {
    this.form.markAsTouched();

    if (this.form.valid) {
      this.authService.login({
        username: this.username.value,
        password: this.password.value
      })
        .subscribe({
          next: (response) => {
            console.log(response);
          },
          error: () => {
            this.form.setErrors({
              invalidLogin: true
            });
          }
        });
    }
  }

  ngOnInit() {
    this.form = new FormGroup({
      'username': new FormControl(null, {
        validators: [
          Validators.required
        ],
        updateOn: 'submit'
      }
      ),
      'password': new FormControl(null,
        {
          validators: [
            Validators.required
          ],
          updateOn: 'submit'
        })
    });
  }
}

<form [formGroup]="form" (ngSubmit)="onSubmit()">
  <div>
    <label>
      Username
      <input placeholder="Username" type="text" formControlName="username">
    </label>
  </div>
  <div>
    <label>
      Password
      <input placeholder="Password" type="password" formControlName="password">
    </label>
  </div>
  <ul *ngIf="form.touched">
    <li *ngIf="username.errors && username.errors.required">
      Username is required
    </li>
    <li *ngIf="password.errors && password.errors.required">
      Password is required
    </li>
    <li *ngIf="form.errors && form.errors.invalidLogin">
      Invalid login credentials
    </li>
  </ul>
  <button type="submit">Send</button>
</form>
